bookers-app2/config/routes.rb
Rails.application.routes.draw do
  # get 'homes/top' =>'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'  
  resources :users, only:[:index,:create,:show,:edit,:update]
  #resources :books, only:[:index,:show,:create,:edit,:destroy]
  resources :books
end

bookers-app2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence: true
  validates :body,presence: true,length: { maximum: 200}
end

bookers-app2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
         attachment :profile_image
         validates :name,presence: true,length: { in: 2..20 }
         validates :introduction,length: { maximum: 50 }
end

bookers-app2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "successfully"
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

bookers-app2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @boook = Book.find(params[:id])
    @user = User.find(@boook.user_id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "You have creatad book successfully."
    redirect_to book_path(@book.id)
  else 
    @books = Book.all
    @user = current_user
    render :index
  end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      flash[:success] ="error"
      redirect_to books_path
    end
  end

  def destroy
    @boook = Book.find(params[:id])
    if @boook.user_id = current_user.id
      @boook.destroy
      redirect_to books_path
    else
      render :show
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:success] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    render :edit
  end
  end
protected
 def book_params
   params.require(:book).permit(:title,:body)
 end
end

bookers-app2/app/controllers/homes_controller.rb
 class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  def top
  end
  
  def about
  end
end

bookers-app2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def create
    user = User.new(user_params)
    user.save
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
    # flash[:success] = 'Welcome! You have signed up successfully.'
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user info successfully.'
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end


protected
 def user_params
   params.require(:user).permit(:name,:profile_image,:introduction)
 end
 def book_params
   params.require(:book).permit(:title,:opinion)
 end
end

   # if @boook.user_id = current_user.id
   #    redirect_to edit_book_path(@boook)
   #  else
   #    render :show
   #  end    

bookers-app2/app/helpers/books_helper.rb
module BooksHelper
end

bookers-app2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers-app2/app/helpers/users_helper.rb
module UsersHelper
end

bookers-app2/app/views/books/edit.html.erb
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error
      <%= @book.errors.full_messages.each do |msg| %>
       <%= msg %>
      <% end %>
    <% end %>


<h2>Editing Book</h2>
  <%= form_for(@book) do |f| %>
    <h5>Title</h5>
    <%= f.text_field :title %>
    <h5>Opinion</h5>
    <%= f.text_area :body %>
    <%= f.submit "Update Book", class:"btn btn-block btn-primary" %>
   <% end %>

bookers-app2/app/views/books/index.html.erb
<div class="container">
  <div class="row">

  <%= render 'users/user_part', book:@book, user:@user %>

<div class="book-index col-9">
  <h2>Books</h2>
    <table>
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
       </tr>
       </thead>
       <tbody>
        
      <% @books.each do |book|%>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpg', fallback: "no_image.jpg" %>
            <% end %>
          </td>          
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>          
          <td><%= book.body %></td>
      <% end %>
       </tbody>
    </table>
</div>    
</div>
</div>
 

bookers-app2/app/views/books/show.html.erb
    <% if flash[:success] %>
      <div class="flash">
        <%= flash[:success] %>
      </div>
    <% end %>

<div class="container">
  <div class="row">

  <%= render 'users/user_part', book:@book, user:@user %>

      <div class="book-detail col-9">
        <h2>Book detail</h2>
        <table>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                 <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg" %><br>
                 <%= @user.name %>
                <% end %>
              </td>
              <td><%= @boook.title %></td>
              <td><%= @boook.body %></td>
              <% if @boook.user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@boook), class:"btn btn-success" %></td>
                <td><%= link_to "Destroy", "/books/#{@boook.id}" , class:"btn btn-danger", method: :delete %></td>
              <% end %>
            </tr>
        </table>
      </div>
    </div>
  </div>

bookers-app2/app/views/homes/about.html.erb
<h1 class="welcome">wellcome to<span class="app-name fas fa-book">Bookers!</span></h1>

bookers-app2/app/views/homes/top.html.erb
<div class="top text-left",style:>
<h1 class="welcome">wellcome to<span class="app-name fas fa-book">Bookers</span>  !!</h1>
<%= flash[:notice] %>
<p class="welcome">
  In<span class="fas fa-book app-name">Bookers,</span><br />
  </p>
  <p class="top-text">
    you can share and exchange your opinions,inpressions,and emotions<br />
    about various books!
    </p>
  <%= link_to "Log in", new_user_session_path,  class:"login-1 btn btn-block" %>
  <%= link_to "Sign up", new_user_registration_path, class:"regisration-3 btn btn-block" %>
</div>

bookers-app2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<div id="header">
  <nav>
      <div class="nav-content clearfix">
       <p class="nav-logo pull-left" ,style:"margin-left:190px;">Bookers</p>
        <ul class="nav navbar-nav navbar-right sticky-top nav-menu">
          <% if user_signed_in? %>
          <li class="nav-item"><%= link_to " Home", user_path(current_user), class:"fas fa-home"%> </li>
          <li class="nav-item"> <%= link_to " Users", users_path, class:"fas fa-user" %> </li>
          <li class="nav-item"> <%= link_to " Books", books_path, class:"fas fa-book" %> </li>
          <li class="nav-item"> <%= link_to " logout", destroy_user_session_path, method: :delete,class:"fas fa-sign-in-alt" %> </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"fas fa-home" %>
          </li>
          <li class="nav-item">
            <%= link_to " About", home_about_path, class:"fas fa-paperclip" %>
          </li>
          <li class="nav-item">
            <%= link_to " sign up", new_user_registration_path, class:"fas fa-pen-square" %>
          </li>
          <li class="nav-item">
            <%= link_to " login", destroy_user_session_path, class:"fas fa-sign-out-alt",method: :delete%>
          </li>
          <% end %>
        </ul>
      </div>
      </nav>
    <div class="container">
      <%= yield %>
      <p class="pull-right">
        CopyRight Infratop.inc
        </p>
    </div>
</div>


</body>
</html>

bookers-app2/app/views/users/_user_part.html.erb
<div class="part-template col-3">  

    <% if book.errors.any? %>
      <%= book.errors.count %>error
      <%= book.errors.full_messages.each do |msg| %>
       <%= msg %>
      <% end %>
    <% end %>
    
 <div class="user-info">
  <h2>User info</h2>
  <table class="temp-table">
    <tr><td><%= attachment_image_tag user, :profile_image, :fill,90,90, format:'jpg', fallback: "no_image.jpg" %></td></tr>
    <tr><th>name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= user.name %></th></tr>
    <tr><th>introduction</th></tr>
    <tr><td><%= user.introduction %></td></tr>
  </table>
  <%= link_to "" , edit_user_path(current_user), class:"fas fa-wrench btn btn-block btn-default" %>
 </div>


  <%= form_for(book) do |f| %>
    <div class="new-book">
      <h2>New book</h2>
      <h5>Title</h5>
      <%= f.text_field :title %>
      <h5>Opinion</h5> 
      <%= f.text_area :body %>
      <%= f.submit "Create Book", class:"btn btn-block btn-primary" %>
    </div>
  <% end %>

</div>

bookers-app2/app/views/users/edit.html.erb
   <% if @user.errors.any? %>
      <%= @user.errors.count %>error
      <%= @user.errors.full_messages.each do |msg| %>
       <%= msg %>
      <% end %>
    <% end %>

<h2>User info</h2>
<%= form_for(@user,url:{controller: "users",action: "update"}) do |f| %>
  <div class="edit-form">
    <h4>Name</h4>
    <%= f.text_field :name, autofocus:true %>
    <h4>Image</h4>
    <%= f.attachment_field :profile_image %>
    <h4>introduction</h4>
    <%= f.text_area :introduction %><br /><br />
    <%= f.submit "Update User", class:"btn btn-sm btn-default" %>
  </div>
<% end %>

bookers-app2/app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <%= render'users/user_part', book:@book, user:@user %>

    <div class="col-9">
    <h2>Users</h2>
      <table>
        <thead>
          <tr>
          <th class="image">image</th>
          <th class="name">name</th>
          <th class="show"></th>
          </tr>
        </thead>
            <tbody>
          <% @users.each do |users|%>
            <tr>
            <td class="image"><%= attachment_image_tag users, :profile_image, :fill,30,30, format:'jpg' %></td>
            <td class="name"><%= users.name%></td>
            <td class="show"><%= link_to "show" ,user_path(users.id) %></td>
            </tr>
          <% end %>
            </tbody>
      </table>
    </div>
  </div>
</div>  

bookers-app2/app/views/users/show.html.erb
<div class="container">
  <div class="row">



<%= render 'users/user_part', book:@book, user:@user %>
<%= flash[:notice] %>

    <div class="mybook col-9">
      <h2>Books</h2>
          <table>
            <thead>
              <tr>
              <th class="space">&nbsp;</th>
               <th class="title">Title</th>
               <th class="opinion">Opinion</th>
               <th class="space">&nbsp;</th>
              </tr>
              </thead>
              <tbody>
                <% @books.each do |books| %>
                <tr>
                  <td class="space"><%= attachment_image_tag books.user, :profile_image, :fill,30,30, format:'jpg', fallback: "no_image.jpg" %></td>
                  <td class="title"><%=link_to books.title, book_path(books.id) %></td>
                  <td class="opinion"><%= books.body %></td>
                  <td class="space">&nbsp;</td>
                </tr>
                <% end %>
                </tbody>
          </table>
    </div>
   </div>
  </div>